<IDX> Starting preview... Waiting for your web server to start serving
> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

<IDX> ▶️ Preview running
   ▲ Next.js 15.2.3 (Turbopack)
   - Local:        http://localhost:9002
   - Network:      http://0.0.0.0:9002

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

 ✓ Ready in 1788ms
 ○ Compiling / ...
 ✓ Compiled / in 10.2s
 GET / 200 in 11099ms
 GET / 200 in 204ms
Error:  ⚠ Blocked cross-origin request from 6000-firebase-studio-1746693118697.cluster-44kx2eiocbhe2tyk3zoyo3ryuo.cloudworkstations.dev. To allow this, configure "allowedDevOrigins" in next.config
Read more: https://nextjs.org/docs/app/api-reference/config/next-config-js/allowedDevOrigins

<IDX> Reloading preview...
<IDX> ▶️ Preview running
<IDX> Reloading preview...
<IDX> ▶️ Preview running
 GET /?monospaceUid=0 200 in 403ms
 GET /?monospaceUid=437575 200 in 291ms
Error:  ⚠ Blocked cross-origin request from 9000-firebase-studio-1746693118697.cluster-44kx2eiocbhe2tyk3zoyo3ryuo.cloudworkstations.dev. To allow this, configure "allowedDevOrigins" in next.config
Read more: https://nextjs.org/docs/app/api-reference/config/next-config-js/allowedDevOrigins

Error: FATAL: An unexpected Turbopack error occurred. Please report the content of /tmp/next-panic-4f1c5feb30997d745cec5210d846563c.log, along with a description of what you were doing when the error occurred, to https://github.com/vercel/next.js/issues/new?template=1.bug_report.yml

Error: [Error [TurbopackInternalError]: Next.js package not found

Debug info:
- Execution of get_entrypoints_with_issues_operation failed
- Execution of EntrypointsOperation::new failed
- Execution of Project::entrypoints failed
- Execution of AppProject::routes failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_loader_tree failed
- Execution of get_next_package failed
- Next.js package not found]

[?25h
<IDX> ✘ Preview shutdown unexpectedly
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

<IDX> ▶️ Preview running
   ▲ Next.js 15.2.3 (Turbopack)
   - Local:        http://localhost:9002
   - Network:      http://0.0.0.0:9002

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

 ✓ Ready in 1788ms
 ○ Compiling / ...
 ✓ Compiled / in 10.2s
 GET / 200 in 11099ms
 GET / 200 in 204ms
Error:  ⚠ Blocked cross-origin request from 6000-firebase-studio-1746693118697.cluster-44kx2eiocbhe2tyk3zoyo3ryuo.cloudworkstations.dev. To allow this, configure "allowedDevOrigins" in next.config
Read more: https://nextjs.org/docs/app/api-reference/config/next-config-js/allowedDevOrigins

<IDX> Reloading preview...
<IDX> ▶️ Preview running
<IDX> Reloading preview...
<IDX> ▶️ Preview running
 GET /?monospaceUid=0 200 in 403ms
 GET /?monospaceUid=437575 200 in 291ms
Error:  ⚠ Blocked cross-origin request from 9000-firebase-studio-1746693118697.cluster-44kx2eiocbhe2tyk3zoyo3ryuo.cloudworkstations.dev. To allow this, configure "allowedDevOrigins" in next.config
Read more: https://nextjs.org/docs/app/api-reference/config/next-config-js/allowedDevOrigins

Error: FATAL: An unexpected Turbopack error occurred. Please report the content of /tmp/next-panic-4f1c5feb30997d745cec5210d846563c.log, along with a description of what you were doing when the error occurred, to https://github.com/vercel/next.js/issues/new?template=1.bug_report.yml

Error: [Error [TurbopackInternalError]: Next.js package not found

Debug info:
- Execution of get_entrypoints_with_issues_operation failed
- Execution of EntrypointsOperation::new failed
- Execution of Project::entrypoints failed
- Execution of AppProject::routes failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_loader_tree failed
- Execution of get_next_package failed
- Next.js package not found]

[?25h
<IDX> ✘ Preview shutdown unexpectedly

Hard Restart

Show Complete Logs